name:                uniformblock-experiment
version:             0.1.0.0
github:              "githubuser/uniformblock-experiment"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- bytestring
- gl
- text
- vector

executables:
  uniformblock:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - GLFW-b
    - shakespeare
